### ISSUE TITLE
Make sure packages files are harvested from npm and ready to use on S3

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub#50] opened 2021-05-18 08:48 UTC
The owner of this task makes sure to understand what are the sub tasks that are needed in order to achieve this goal. They create the relevant sub-tasks under PLANNED. 

For example: 
- What do we need in order to productize the existing code that harvests the packages from npm? (testing? monitoring? else?)

Please speak with Elad about it.

**Comment by RomainMuller** [comment] 2021-05-26 08:33
Duplicate of #4 ?

**Closed** 2021-06-20 12:17 UTC
