### ISSUE TITLE
Implement: package ingestion and processing

### ISSUE THREAD

**Issue by MrArnoldPalmer** [cdklabs/construct-hub#54] opened 2021-05-24 16:28 UTC
Adds a lambda function that triggers from a dynamo DB stream to add make a new version of a package, or newly published package, available in construct-hub. The dynamo stream contains change events from relevant packages and includes the package scope, name, and version to be processed as described in https://github.com/cdklabs/construct-hub/issues/55.

The lambda will download the package artifacts from npm and store the relevant ones, .jsii and readme.md, in the target s3 bucket. No processing should be performed on the package artifacts as part of this task. This bucket should be made accessible to the construct-hub-webapp frontend via cloudfront.

**Comment by RomainMuller** [comment] 2021-05-26 08:34
Duplicate of #3 and #4

**Closed by RomainMuller** 2021-05-26 08:34 UTC
Labels: effort/small, risk/low
